// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kebuztwhahtmiloztcke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlYnV6dHdoYWh0bWlsb3p0Y2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzkxNDIsImV4cCI6MjA3MTk1NTE0Mn0.xJ3XzbQzHUV288gMqUzlS9Rl39do42S4lDRzAsIQ4eM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});